runtime: nodejs16 # or another supported version
 
 
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
 
default_expiration: "4d 5h"

handlers:
- url: /stylesheets
  static_files: dist/index.html
  upload: dist/index.html

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html